[package]
name = "oxidize-web"
version = "0.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
bytes = "0.5.4"
hyper = "0.13.5"
tokio = { version = "0.2.0", features = ["full"] }
anyhow = "1.0.28"
thiserror = "1.0.16"
serde = { version = "1.0.106", features = ["rc", "derive"] }
serde_json = "1.0.52"
serde_cbor = "0.11.1"
toml = "0.5.6"
serde_urlencoded = "0.6.1"
futures = "0.3.4"
log = "0.4.8"
pretty_env_logger = "0.4.0"
reqwest = "0.10.4"
chrono = { version = "0.4.11", features = ["serde"] }
clap = "2.33.0"
rust-embed = { version = "5.5.1", features = ["interpolate-folder-path"] }
mime_guess = "2.0.3"
mime = "0.3.16"
smallvec = "1.4.0"
cookie = { version = "0.13.3", features = ["percent-encode"] }
base64 = "0.12.1"
time = "0.2.15"
async-oauth2 = "0.2.0"
url = { version = "2.1.1", features = ["serde"] }
parking_lot = "0.10.2"
sled28 = { package = "sled", version = "0.28.0" }
sled31 = { package = "sled", version = "0.31.0" }
ring = "0.16.13"
relative-path = { version = "1.0.0", features = ["serde"] }
pin-utils = "0.1.0"
